# Generated by Django 2.1.2 on 2019-03-30 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img')),
                ('reg_no', models.CharField(max_length=10)),
                ('dep', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=8)),
                ('tutor', models.CharField(max_length=20)),
                ('warden', models.CharField(max_length=20)),
                ('parent_no', models.CharField(max_length=10)),
                ('student_no', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
